image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

include:
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

variables:
  SECURE_LOG_LEVEL: info
  DS_JAVA_VERSION: 11
  DOCKER_DRIVER: overlay
  CONTAINER_IMAGE: smartcommunitylab/challenges-generator:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  CONTAINER_IMAGE_LATEST: smartcommunitylab/challenges-generator:$CI_COMMIT_REF_NAME-latest
  CS_IMAGE: smartcommunitylab/challenges-generator:$CI_COMMIT_REF_NAME-latest
  CONTAINER_CACHE_IMAGE: smartcommunitylab/challenges-generator:cache
  SAST_JAVA_VERSION: 11

update-backend-cache-image:
  stage: build
  variables:
    BUILDKIT_PROGRESS: plain
    DOCKER_BUILDKIT: 1 
  script:
    - docker login -u $DHUB_USER -p $DHUB_PASS
    - docker build --build-arg REPO=$CI_COMMIT_REF_NAME -f Dockerfile-cache -t $CONTAINER_CACHE_IMAGE .
    - docker push $CONTAINER_CACHE_IMAGE
  rules:
    - changes:
      - pom.xml

backend-container-build:
  stage: build
  script:
    - docker login -u $DHUB_USER -p $DHUB_PASS
    - DOCKER_BUILDKIT=1 docker build -f Dockerfile --build-arg REPO=$CI_COMMIT_REF_NAME -t $CONTAINER_IMAGE -t $CONTAINER_IMAGE_LATEST . --no-cache
    - docker push $CONTAINER_IMAGE
    - docker push $CONTAINER_IMAGE_LATEST
  only:
    - playAndGo-dev
    - playAndGo-prod
    - master
  artifacts:
    expire_in: 1 week
    
container_scanning:
  stage: test
  variables:
    DOCKER_IMAGE: smartcommunitylab/challenges-generator:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
    DOCKERFILE_PATH: "Dockerfile"
    GIT_STRATEGY: fetch
    DOCKER_USER: ""
    DOCKER_PASSWORD: ""
  artifacts:
    expire_in: 1 week
  dependencies:
    - backend-container-build
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
    
spotbugs-sast:
  rules:
     - if: '$CI_COMMIT_REF_NAME == "master"'

semgrep-sast:
  rules:
     - if: '$CI_COMMIT_REF_NAME == "master"'

nodejs-scan-sast:
  rules:
     - if: '$CI_COMMIT_REF_NAME == "master"'

gemnasium-maven-dependency_scanning:
  rules:
     - if: '$CI_COMMIT_REF_NAME == "master"'

gemnasium-dependency_scanning:
  rules:
     - if: '$CI_COMMIT_REF_NAME == "master"'

deploy-dev:
  stage: deploy
  image: smartcommunitylab/kubectl-alpine:latest
  environment:
    name: dslab
  script:
    - echo "deploy backend"
    - kubectl -n playngo-dev set image deployments/challenges-generator challenges-generator=$CONTAINER_IMAGE --record=true
    - kubectl -n playngo-dev rollout status deployment challenges-generator
  only:
    - playAndGo-dev
  artifacts:
    expire_in: 1 week

deploy-prod:
  stage: deploy
  image: smartcommunitylab/kubectl-alpine:latest
  environment:
    name: dslab
  script:
    - echo "deploy backend"
    - kubectl -n playngo-prod set image deployments/challenges-generator challenges-generator=$CONTAINER_IMAGE --record=true
    - kubectl -n playngo-prod rollout status deployment challenges-generator
  only:
    - playAndGo-prod
  artifacts:
    expire_in: 1 week