version: "3"

services:
  challenge-generator:
    build:
      context: .
      args:
        - REPO=master
    container_name: challenge-generator
    ports:
      - "8020:8020"
    env_file: challenge-gen.env
    volumes:
      - ./config:/home/challenges/config
