FROM maven:3-eclipse-temurin-11-alpine AS build
ARG REPO
RUN apk --no-cache add git
RUN git clone -b $REPO https://github.com/smartcommunitylab/game-engine.challenge-gen.git && cd game-engine.challenge-gen && mvn clean install -Dmaven.test.skip=true
ADD pom.xml /tmp
ADD src/ /tmp/src/ 
WORKDIR /tmp
RUN mvn clean package -P full-client-jar -DskipTests

FROM scratch
COPY --from=build /root/.m2 /root/.m2