server:
    port: ${SERVER_PORT:8020}
    servlet:
      context-path: ${SERVER_CONTEXTPATH:/challenge-generator}

config:
  url: ${GAMIFICATION_URL:}
  api_user: ${API_USER:}
  api_pass: ${API_PASS:}
  challengeUrl: ${CHALLENGE_URL:}
  scheduleUrl: ${SCHEDULE_URL:}
  postgresUrl: ${POSTGRES_URL:}
  
openapi:
   version: 1.0.0
   license: Apache License, Version 2.0
   licenseUrl: http://www.apache.org/licenses/LICENSE-2.0
   contact:
      name: DS Lab
      url: www.smartcommunitylab.it
      email: info@smartcommunitylab.it
                      
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
  api-docs:
    path: /challenge-generator/v3/api-docs
