games:
  - gameId: 6437ddadf8e59353e50d143e 
    standardSingleChallenges:
      levelStrategies:
        - level:
            type: Green Warrior
            index: 0
          strategy: empty
        - level:
            type: Green Warrior
            index: 1
          strategy: fixedOne
        - level:
            type: Green Warrior
            index: 2
          strategy: choiceTwoV2
        - level:
            type: Green Warrior
            index: 3
          strategy: choiceThreeV2
      settings:
        start: 2023-04-17 00:00
        duration: 7d
        suspensions:
        modeConcepts:
          - Walk_Km
          - Bike_Km
          - green leaves
        hide: True
      playerSet:
      reward:
        scoreName: green leaves
        type: fixed
        value: 100.0
        maxValue:
    standardGroupChallenges:
      settings:
        start: 2023-04-17 00:00
        duration: 7d
        model: groupCooperative
        modeConcepts:
          - Walk_Km
          - Bike_Km
          - green leaves
      playerSet:
      reward:
        scoreName: green leaves
        type: 
        value:
        maxValue:
    specialSingleChallenges: 
      - settings:
          start: 2023-04-17 00:00
          duration: 7d
          model: survey
          fields:
            surveyType: bellaCoincidenza
            link : ""    
          hide: False
        playerSet:
        reward:
          scoreName: green leaves
          type: fixed
          value: 250.0
          maxValue: 
 
